version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart-chat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3323:3306