definitions:
  dto.ChatMessageRequest:
    properties:
      chat_id:
        type: integer
      question:
        type: string
      user_id:
        type: string
    type: object
  dto.ChatMessageResponse:
    properties:
      answer:
        type: string
    type: object
  dto.ChatResponse:
    properties:
      chat_id:
        type: integer
    type: object
  dto.Error:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /smart-chat/v1/chat:
    post:
      consumes:
      - application/json
      description: '- create a chat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ChatResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - ApiKeyAuth: []
      summary: '- create a chat'
      tags:
      - '- Chat'
  /smart-chat/v1/chat-message:
    post:
      consumes:
      - application/json
      description: '- create a chat-message'
      parameters:
      - description: chatMessageRequest
        in: body
        name: chatMessageRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ChatMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ChatMessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - ApiKeyAuth: []
      summary: '- create a chat-message'
      tags:
      - '- Chat-Message'
  /smart-chat/v1/health:
    get:
      consumes:
      - application/json
      description: '- healthcheck'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: '- healthcheck'
      tags:
      - '- Health'
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
